# Generated by Django 2.2.7 on 2020-01-16 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Localtion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='untitled location', max_length=120)),
                ('street', models.CharField(default='untitled street', max_length=300)),
                ('sub_district', models.CharField(default='untitled sub district', max_length=120)),
                ('city', models.CharField(default='untitled city', max_length=120)),
                ('province_or_state', models.CharField(default='untitled province', max_length=120)),
                ('country', models.CharField(default='untitled country', max_length=120)),
                ('postal_code', models.DecimalField(decimal_places=0, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='untitled event', max_length=120)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('topic', models.CharField(default='untitled topic', max_length=120)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketing.Localtion')),
            ],
        ),
    ]
