# Generated by Django 2.2.7 on 2020-01-17 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0002_auto_20200117_1510'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Localtion',
            new_name='Location',
        ),
    ]
