# Generated by Django 2.2.7 on 2020-01-17 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0003_auto_20200117_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(blank=True, choices=[('SM', 'Seminar'), ('HO', 'Hand On'), ('PL', 'Pelatihan'), ('WS', 'Workshop'), ('SW', 'Seminar dan workshop')], max_length=2),
        ),
    ]
