# Generated by Django 2.2.7 on 2020-01-23 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0008_event_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_participant',
            name='pay_status',
            field=models.BooleanField(default=False),
        ),
    ]
