# Generated by Django 2.2.7 on 2020-01-26 07:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0009_event_participant_pay_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event_file',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=255, null=True, upload_to='')),
                ('date_created', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
