# Generated by Django 2.2.7 on 2020-01-26 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0010_event_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event_file',
        ),
    ]
