# Generated by Django 2.2.7 on 2020-02-01 04:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0017_event_due_registeration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='due_registeration',
        ),
        migrations.AddField(
            model_name='event',
            name='due_registration',
            field=models.DateField(default=datetime.datetime(2020, 1, 29, 11, 28, 31, 16921)),
        ),
    ]
