# Generated by Django 2.2.7 on 2020-02-02 15:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0018_auto_20200201_1128'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateTimeField(default=datetime.datetime(2020, 2, 4, 15, 22, 55, 351695, tzinfo=utc))),
                ('pay_status', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='eventparticipant',
            name='pay_status',
        ),
        migrations.AlterField(
            model_name='event',
            name='due_registration',
            field=models.DateField(default=datetime.datetime(2020, 1, 30, 22, 22, 55, 351695)),
        ),
    ]
