# Generated by Django 2.2.7 on 2020-02-02 15:26

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0019_auto_20200202_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventparticipant',
            name='payment',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='ticketing.EventPayment'),
        ),
        migrations.AlterField(
            model_name='event',
            name='due_registration',
            field=models.DateField(default=datetime.datetime(2020, 1, 30, 22, 26, 14, 531063)),
        ),
        migrations.AlterField(
            model_name='eventpayment',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 4, 15, 26, 14, 531063, tzinfo=utc)),
        ),
    ]
