# Generated by Django 2.2.7 on 2020-02-05 23:41

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_auto_20200206_0641'),
        ('ticketing', '0028_auto_20200206_0635'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventparticipant',
            name='invoice',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.Invoice'),
        ),
        migrations.AlterField(
            model_name='event',
            name='due_registration',
            field=models.DateField(default=datetime.datetime(2020, 2, 3, 6, 41, 9, 111568)),
        ),
        migrations.AlterField(
            model_name='eventpayment',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 7, 23, 41, 9, 115658, tzinfo=utc)),
        ),
    ]
