# Generated by Django 2.2.7 on 2020-02-15 05:04

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0043_auto_20200215_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='due_registration',
            field=models.DateField(default=datetime.datetime(2020, 2, 12, 12, 4, 35, 91916)),
        ),
        migrations.AlterField(
            model_name='eventparticipant',
            name='invoice',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.Invoice'),
        ),
        migrations.AlterField(
            model_name='eventpayment',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 17, 5, 4, 35, 95904, tzinfo=utc)),
        ),
    ]
