# Generated by Django 2.2.7 on 2020-02-18 07:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0045_auto_20200215_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventparticipant',
            name='barcode',
            field=models.ImageField(blank=True, null=True, upload_to='images/barcode/ticket/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='due_registration',
            field=models.DateField(default=datetime.datetime(2020, 2, 15, 14, 47, 1, 165825)),
        ),
        migrations.AlterField(
            model_name='eventpayment',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 20, 7, 47, 1, 165825, tzinfo=utc)),
        ),
    ]
