# Generated by Django 2.2.7 on 2020-02-18 14:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0046_auto_20200218_1447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventparticipant',
            name='payment',
        ),
        migrations.AlterField(
            model_name='event',
            name='due_registration',
            field=models.DateField(default=datetime.datetime(2020, 2, 15, 21, 48, 40, 171939)),
        ),
        migrations.AlterField(
            model_name='eventparticipant',
            name='barcode',
            field=models.URLField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='eventpayment',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 20, 14, 48, 40, 175943, tzinfo=utc)),
        ),
    ]
