# Generated by Django 2.2.7 on 2020-02-18 15:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0048_auto_20200218_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='google_maps',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='due_registration',
            field=models.DateField(default=datetime.datetime(2020, 2, 15, 22, 24, 52, 770383)),
        ),
        migrations.AlterField(
            model_name='eventpayment',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 20, 15, 24, 52, 770383, tzinfo=utc)),
        ),
    ]
