# Generated by Django 2.2.7 on 2020-02-19 02:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0049_auto_20200218_2224'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='untitled document', max_length=150)),
                ('date_of_release', models.DateField(auto_now=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='media/document/pdf/')),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='due_registration',
            field=models.DateField(default=datetime.datetime(2020, 2, 16, 9, 11, 42, 433398)),
        ),
        migrations.AlterField(
            model_name='eventpayment',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 21, 2, 11, 42, 434395, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='event',
            name='document',
            field=models.ManyToManyField(related_name='event_document', to='ticketing.Document'),
        ),
    ]
