# Generated by Django 2.2.7 on 2020-02-19 08:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0051_auto_20200219_0913'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricePlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=20)),
                ('role', models.CharField(blank=True, choices=[('PR', 'perawat'), ('DR', 'dokter'), ('BD', 'bidan'), ('OT', 'other')], max_length=2)),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='due_registration',
            field=models.DateField(default=datetime.datetime(2020, 2, 16, 15, 4, 34, 497706)),
        ),
        migrations.AlterField(
            model_name='eventpayment',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 21, 8, 4, 34, 501706, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='event',
            name='price_plan',
            field=models.ManyToManyField(related_name='event_price_plan', to='ticketing.PricePlan'),
        ),
    ]
