# Generated by Django 2.2.7 on 2020-02-05 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unnamed Account', max_length=20)),
                ('provider', models.CharField(default='Unnamed Provider', max_length=20)),
                ('number', models.IntegerField(default=0)),
            ],
        ),
    ]
