# Generated by Django 2.2.7 on 2020-02-05 23:28

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_account_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False)),
                ('release_date', models.DateField(auto_now=True)),
                ('due_date', models.DateTimeField(default=datetime.datetime(2020, 2, 7, 23, 28, 32, 625367, tzinfo=utc))),
                ('Account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.Account')),
            ],
        ),
    ]
