# Generated by Django 2.2.7 on 2020-02-05 23:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 7, 23, 30, 30, 998791, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='release_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
