# Generated by Django 2.2.7 on 2020-02-05 23:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_auto_20200206_0633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 7, 23, 35, 14, 580266, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='number',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
