# Generated by Django 2.2.7 on 2020-02-05 23:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_auto_20200206_0635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 7, 23, 41, 9, 111568, tzinfo=utc)),
        ),
    ]
