# Generated by Django 2.2.7 on 2020-02-05 23:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_auto_20200206_0641'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='role',
            field=models.CharField(blank=True, choices=[('1', 'Company'), ('2', 'User')], max_length=1),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 7, 23, 45, 54, 196246, tzinfo=utc)),
        ),
    ]
