# Generated by Django 2.2.7 on 2020-02-06 04:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0010_auto_20200206_0734'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='Account',
            new_name='account',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 8, 4, 18, 44, 278945, tzinfo=utc)),
        ),
    ]
