# Generated by Django 2.2.7 on 2020-02-06 04:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0011_auto_20200206_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 8, 4, 18, 53, 842228, tzinfo=utc)),
        ),
    ]
