# Generated by Django 2.2.7 on 2020-02-06 07:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0012_auto_20200206_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2020, 2, 8, 7, 42, 43, 803510, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='release_date',
            field=models.DateField(auto_now=True),
        ),
    ]
