# Generated by Django 2.2.7 on 2020-02-06 07:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0013_auto_20200206_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2020, 2, 8, 7, 45, 15, 555525, tzinfo=utc)),
        ),
    ]
