# Generated by Django 2.2.7 on 2020-02-07 09:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0016_auto_20200207_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 9, 9, 28, 57, 886921, tzinfo=utc)),
        ),
    ]
