# Generated by Django 2.2.7 on 2020-02-13 14:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0017_auto_20200207_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 15, 14, 32, 26, 812940, tzinfo=utc)),
        ),
    ]
