# Generated by Django 2.2.7 on 2020-02-13 15:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0020_auto_20200213_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 15, 15, 35, 20, 170134, tzinfo=utc)),
        ),
    ]
