# Generated by Django 2.2.7 on 2020-02-15 02:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0021_auto_20200213_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='account_type',
            field=models.CharField(blank=True, choices=[('1', 'Bank'), ('2', 'another type')], max_length=1),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 17, 2, 49, 12, 300455, tzinfo=utc)),
        ),
    ]
