# Generated by Django 2.2.7 on 2020-02-15 06:05

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0023_auto_20200215_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.Account'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 17, 6, 5, 31, 852811, tzinfo=utc)),
        ),
    ]
