# Generated by Django 2.2.7 on 2020-02-18 14:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0027_auto_20200218_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 20, 14, 53, 14, 645467, tzinfo=utc)),
        ),
    ]
