# Generated by Django 2.2.7 on 2020-02-19 02:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0029_auto_20200218_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 21, 2, 11, 42, 174665, tzinfo=utc)),
        ),
    ]
