# Generated by Django 2.2.7 on 2020-02-19 02:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0030_auto_20200219_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 21, 2, 13, 22, 576320, tzinfo=utc)),
        ),
    ]
