# Generated by Django 2.2.7 on 2020-02-19 08:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0031_auto_20200219_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 21, 8, 4, 34, 81284, tzinfo=utc)),
        ),
    ]
