# Generated by Django 3.0.3 on 2020-02-24 04:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0032_auto_20200219_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 26, 4, 14, 46, 897080, tzinfo=utc)),
        ),
    ]
