# Generated by Django 3.0.3 on 2020-02-26 15:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0033_auto_20200224_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 28, 15, 0, 5, 694940, tzinfo=utc)),
        ),
    ]
