# Generated by Django 3.0.3 on 2020-02-27 15:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0034_auto_20200226_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 29, 15, 3, 15, 556825, tzinfo=utc)),
        ),
    ]
