# Generated by Django 2.2.7 on 2020-01-11 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
        migrations.AddField(
            model_name='profile',
            name='image_profile',
            field=models.ImageField(default='assets/images/profile/default/icons8-user-100.png', upload_to='assets/images/profile/'),
        ),
    ]
