# Generated by Django 2.2.7 on 2020-01-11 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20200111_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image_profile',
            field=models.ImageField(default='images/profile/default/icons8-user-100.png', upload_to='images/profile/'),
        ),
    ]
